bp/grupos/urls.py
from django.urls import path, include

from . import views

app_name = "grupos"

seccion_urls = ([
    path('~nuevo/', views.SeccionCreateView.as_view(), name='create'),
    path('<slug:slug>/', views.SeccionDetailView.as_view(), name='detail'),
    path('<slug:slug>/~editar/', views.SeccionUpdateView.as_view(),
         name='update'),
], 'secciones')

urlpatterns = [
    path('', views.GrupoListView.as_view(), name='list'),
    path('~nuevo/', views.GrupoCreateView.as_view(), name='create'),
    path('<slug:slug>/', views.GrupoDetailView.as_view(), name='detail'),
    path('<slug:slug>/~editar/', views.GrupoUpdateView.as_view(),
         name='update'),
    path('<slug:grupo_slug>/secciones/', include(seccion_urls))
]

bp/personas/urls.py
from django.urls import path

from . import views

app_name = "personas"
urlpatterns = [
    path('', views.PersonaListView.as_view(), name='list'),
    path('<slug:grupo_slug>/~nueva/', views.PersonaCreateView.as_view(),
         name='create'),
    path('<slug:slug>/', views.PersonaDetailView.as_view(), name='detail'),
    path('<slug:slug>/~editar/', views.PersonaUpdateView.as_view(),
         name='update'),
]

bp/users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"
urlpatterns = [
    url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    url(
        r"^about/$",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^users/", include("bp.users.urls", namespace="users")),
    url(r"^accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    url(r"^grupos/", include("bp.grupos.urls")),
    url(r"^personas/", include("bp.personas.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

bp/grupos/models.py
from django.db import models
from django import urls

import autoslug

from . import constants


class Grupo(models.Model):
    """Representa un grupo scout."""
    nombre = models.CharField(max_length=255)
    numero = models.IntegerField(blank=True, null=True)
    direccion = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)
    telefono = models.CharField(max_length=32, blank=True)
    slug = autoslug.AutoSlugField(populate_from='nombre')
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        if not self.numero:
            return f'Grupo Scout S/N - {self.nombre}'
        return f'Grupo Scout Nº{self.numero} - {self.nombre}'

    def get_absolute_url(self):
        return urls.reverse('grupos:detail', kwargs={'slug': self.slug})


class Seccion(models.Model):
    """Representa una sección del grupo scout.

    Los integrantes del grupo scout pertenecen a una sección. Esta sección
    pertenece a una rama y puede ser unidad mixta, femenina o masculina.

    Algunos integrantes pueden pertenecer a mas de una sección:
      * Dirigentes de más una sección
      * Rovers en servicio
    """
    grupo = models.ForeignKey(Grupo, related_name='secciones',
                              on_delete=models.CASCADE)
    rama = models.PositiveIntegerField(choices=constants.RAMAS)
    unidad = models.PositiveIntegerField(choices=constants.UNIDADES)
    nombre = models.CharField(max_length=255, blank=True)
    lema = models.CharField(max_length=255, blank=True)
    slug = autoslug.AutoSlugField(populate_from='populate_slug')

    def __str__(self):
        return (f'{self.nombre} - {self.get_rama_display()} Unidad '
                f'{self.get_unidad_display()}')

    def populate_slug(self):
        """Funcion para completar el slug utilizado en la url amigable."""
        return f'{self.get_rama_display()}-{self.nombre}'

    def get_absolute_url(self):
        return urls.reverse(
            'grupos:secciones:detail',
            kwargs={'grupo_slug': self.grupo.slug, 'slug': self.slug}
        )

    def get_update_url(self):
        return urls.reverse(
            'grupos:secciones:update',
            kwargs={'grupo_slug': self.grupo.slug, 'slug': self.slug}
        )

bp/personas/models.py
from django.db import models
from django.urls import reverse

import autoslug


BENEFICIARIO = 'BENEFICIARIO'
ACTIVO = 'ACTIVO'
ADHERENTE = 'ADHERENTE'

TIPO_MIEMBROS = (
    (BENEFICIARIO, 'BENEFICIARIO/A'),
    (ACTIVO, 'ACTIVO/A'),
    (ADHERENTE, 'ADHERENTE'),
)


class Persona(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    slug = autoslug.AutoSlugField(populate_from='nombre_completo')
    dni = models.CharField(blank=True, max_length=255)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    seccion = models.ForeignKey('grupos.Seccion', related_name='personas',
                                null=True, blank=True,
                                on_delete=models.SET_NULL)
    grupo = models.ForeignKey('grupos.Grupo', related_name='personas',
                              null=True, blank=True,
                              on_delete=models.SET_NULL)
    # TODO add cargo (app asociaciones) many to many
    tipo_miembro = models.CharField(choices=TIPO_MIEMBROS, max_length=12,
                                    blank=True)
    email = models.EmailField(blank=True)
    telefono = models.CharField(max_length=32, blank=True)
    celular = models.CharField(max_length=32, blank=True)
    direccion = models.CharField(max_length=255, blank=True)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre_completo

    @property
    def nombre_completo(self):
        return f'{self.apellido.upper()}, {self.nombre}'

    def get_absolute_url(self):
        return reverse('personas:detail', kwargs={'slug': self.slug})

bp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

bp/grupos/forms.py
from django import forms

from . import models


class SeccionForm(forms.ModelForm):
    class Meta:
        model = models.Seccion
        fields = ('rama', 'unidad', 'nombre', 'lema')

    def __init__(self, grupo, *args, **kwargs):
        self.grupo = grupo
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        """Asocia la seccion con el grupo pasado por parametro."""
        seccion = super().save(commit=False)
        seccion.grupo = self.grupo
        if commit:
            seccion.save()
        return seccion

bp/personas/forms.py
import datetime

from django import forms

from . import models


year = datetime.date.today().year


class PersonaForm(forms.ModelForm):
    class Meta:
        model = models.Persona
        fields = (
            "apellido",
            "nombre",
            "dni",
            "fecha_nacimiento",
            "seccion",
            "tipo_miembro",
            "email",
            "telefono",
            "celular",
            "direccion",
        )
        widgets = {
            "fecha_nacimiento": forms.SelectDateWidget(
                years=range(year - 4, year - 80, -1)
            )
        }

    def __init__(self, grupo, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.grupo = grupo
        self.fields["seccion"].queryset = self.grupo.secciones.all()

bp/grupos/views.py
from django import shortcuts
from django.views import generic

import django_tables2

from . import (
    forms,
    models,
    tables,
)


class GrupoMixin:
    """Agrega el grupo al contexto.

    Obtiene el grupo desde el parametro ``grupo_slug` en la URL.
    """
    def get_grupo(self):
        """Obtiene el grupo desde el parametro ``grupo_slug` en la URL."""
        return shortcuts.get_object_or_404(models.Grupo,
                                           slug=self.kwargs['grupo_slug'])

    def get_context_data(self, **kwargs):
        """Agrega grupo al contexto."""
        return super().get_context_data(grupo=self.get_grupo(), **kwargs)


class GrupoListView(django_tables2.SingleTableView):
    """Muestra lista de grupos."""
    model = models.Grupo
    table_class = tables.GrupoTable
    paginate_by = 20
    ordering = ('nombre',)


class GrupoDetailView(django_tables2.SingleTableMixin, generic.DetailView):
    """Muestra detalles de un grupo. Tambien muestra las secciones"""
    model = models.Grupo
    table_class = tables.SeccionTable

    def get_table_data(self):
        """Obtiene las secciones a mostrar."""
        return self.get_object().secciones.all()



class GrupoUpdateView(generic.UpdateView):
    """Edita datos de un grupo."""
    model = models.Grupo
    fields = ('nombre', 'numero', 'direccion', 'email', 'telefono')


class GrupoCreateView(generic.CreateView):
    """Crea un grupo nuevo."""
    model = models.Grupo
    fields = ('nombre', 'numero', 'direccion', 'email', 'telefono')


class SeccionDetailView(GrupoMixin, generic.DetailView):
    """Muestra detalles de una seccion"""
    model = models.Seccion


class SeccionCreateView(GrupoMixin, generic.CreateView):
    """Crea una seccion nueva."""
    model = models.Seccion
    form_class = forms.SeccionForm

    def get_form_kwargs(self):
        data = super().get_form_kwargs()
        data['grupo'] = self.get_grupo()
        return data


class SeccionUpdateView(GrupoMixin, generic.UpdateView):
    """Edita una seccion."""
    model = models.Seccion
    fields = ('rama', 'unidad', 'nombre', 'lema')

bp/personas/views.py
from django import shortcuts
from django.views import generic

import django_tables2

from bp.grupos.models import Grupo

from . import forms, models, tables


class PersonaListView(django_tables2.SingleTableView):
    """Muestra lista de personas."""

    model = models.Persona
    table_class = tables.PersonaTable
    paginate_by = 20
    ordering = ("apellido", "nombre")


class PersonaDetailView(generic.DetailView):
    """Muestra detalles de una persona"""

    model = models.Persona


class PersonaUpdateView(generic.UpdateView):
    """Edita datos de una persona."""

    model = models.Persona
    form_class = forms.PersonaForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["grupo"] = self.object.grupo
        return kwargs


class PersonaCreateView(generic.CreateView):
    """Crea una persona nueva."""

    model = models.Persona
    form_class = forms.PersonaForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["grupo"] = self.get_grupo()
        return kwargs

    def get_grupo(self):
        return shortcuts.get_object_or_404(
            Grupo, slug=self.kwargs["grupo_slug"]
        )

bp/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

bp/templates/grupos/grupo_detail.html
{% extends "base.html" %}
{% load static i18n django_tables2 %}

{% block title %}{{ grupo }}{% endblock %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'grupos:list' %}">Grupos</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ grupo }}</li>
    </ol>
  </nav>

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ grupo.nombre }}</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <a href='{% url 'grupos:update' grupo.slug %}'>Editar</a>
    </div>
  </div>

  <table class="table">
    <tr><th>Numero</th><td>{{ grupo.numero }}</td></tr>
    <tr><th>Direccion</th><td>{{ grupo.direccion|default:'-' }}</td></tr>
    <tr><th>Email</th><td>{{ grupo.email }}</td></tr>
    <tr><th>Telefono</th><td>{{ grupo.telefono }}</td></tr>
  </table>

  <h3>Secciones</h3>
  <div class="row">
    <div class="col-sm-12">
      <a href='{% url 'grupos:secciones:create' grupo.slug %}'>Crear sección</a>
    </div>
  </div>
  {% if table.data %}
    {% render_table table %}
  {% else %}
    <p>No hay secciones. Por favor cree una nueva sección
       <a href='{% url 'grupos:secciones:create' grupo.slug %}'>Crear sección</a>
    </p>
  {% endif %}

  <small>
    Creado: {{ grupo.creado }}
    Ultima actualización: {{ grupo.actualizado }}
  </small>

</div>
{% endblock content %}

bp/templates/grupos/grupo_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ grupo }}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'grupos:list' %}">Grupos</a></li>
      {% if grupo %}
        <li class="breadcrumb-item"><a href="{{ grupo.get_absolute_url }}">{{ grupo }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
      {% else %}
        <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
      {% endif %}
    </ol>
  </nav>
  <h1>{{ grupo.nombre }}</h1>
  <form class="form-horizontal" method="post" action=".">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Guardar</button>
      </div>
    </div>
  </form>
{% endblock %}

bp/templates/grupos/grupo_list.html
{% extends "base.html" %}
{% load static i18n django_tables2 %}
{% block title %}Grupos{% endblock %}

{% block content %}
<div class="container">
  <h2>Grupos</h2>

  <div class="row">
    <div class="col-sm-12">
      <a href='{% url 'grupos:create' %}'>Nuevo</a>
    </div>
  </div>

  {% render_table table %}
</div>
{% endblock content %}

bp/templates/grupos/seccion_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ seccion }}{% endblock %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'grupos:list' %}">Grupos</a></li>
      <li class="breadcrumb-item"><a href="{{ grupo.get_absolute_url }}">{{ grupo }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ seccion }}</li>
    </ol>
  </nav>

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ seccion.nombre }}</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <a href="{{ seccion.get_update_url }}">Editar</a>
    </div>
  </div>

  <table class="table">
    <tr><th>Grupo</th><td>{{ grupo }}</td></tr>
    <tr><th>Rama</th><td>{{ seccion.get_rama_display }}</td></tr>
    <tr><th>Sección</th><td>{{ seccion.get_unidad_display }}</td></tr>
    <tr><th>Nombre</th><td>{{ seccion.nombre }}</td></tr>
    <tr><th>Lema</th><td>{{ seccion.lema }}</td></tr>
  </table>

  <small>
    Creado: {{ seccion.creado }}
    Ultima actualización: {{ seccion.actualizado }}
  </small>

</div>
{% endblock content %}

bp/templates/grupos/seccion_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ seccion }}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'grupos:list' %}">Grupos</a></li>
      <li class="breadcrumb-item"><a href="{% url 'grupos:detail' grupo.slug %}">{{ grupo }}</a></li>
      {% if seccion %}
        <li class="breadcrumb-item"><a href="{{ seccion.get_absolute_url }}">{{ seccion }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
      {% else %}
        <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
      {% endif %}
    </ol>
  </nav>
  <h1>{{ seccion.nombre }}</h1>
  <form class="form-horizontal" method="post" action=".">{% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Guardar</button>
      </div>
    </div>
  </form>
{% endblock %}